In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/boaz

/content/drive/MyDrive/boaz

In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

### __연상이미지__
* https://www.culture.go.kr/bigdata/user/data_market/detail.do?id=28262650-3604-11eb-af9a-4b03f0a582d6

In [ ]:
연상 = pd.read_csv('BOAZXNIA/REMIND_IMAGE_INFO_2021(연상이미지).csv')
연상

,IMAGE_NM,MALE_RATE,FEMALE_RATE,ALL_N10S_RATE,ALL_N20S_RATE,ALL_N30S_RATE,ALL_N40S_RATE,ALL_N50S_RATE,REPRT_YEAR_CN,EXAMIN_COUNTRY_NM
0,"한국 음식(김치, 김, 볼고기 등)",16.4,16.4,18.4,16.0,19.2,10.1,16.7,2021,중국
1,드라마,10.8,12.0,14.4,11.2,12.8,9.0,2.8,2021,중국
2,뷰티 서비스(성형),7.2,10.0,9.6,8.0,10.4,6.7,5.6,2021,중국
3,뷰티 제품(화장품),4.0,7.6,8.0,8.0,4.0,1.1,8.3,2021,중국
4,한글(한국어),4.0,6.8,4.8,8.0,3.2,4.5,8.3,2021,중국
...,...,...,...,...,...,...,...,...,...,...
2271,북한,4.5,3.0,1.0,7.0,2.0,6.0,0.0,2015,남아공
2272,영화,4.5,2.5,3.0,10.0,1.0,0.0,0.0,2015,남아공
2273,태권도,4.5,1.0,1.0,1.0,5.0,1.2,17.6,2015,남아공
2274,관광지,3.5,2.0,5.0,1.0,2.0,2.4,5.9,2015,남아공
2275,한국전쟁,1.0,4.0,0.0,5.0,4.0,1.2,0.0,2015,남아공

In [ ]:
print(연상.REPRT_YEAR_CN.unique())
print(연상.EXAMIN_COUNTRY_NM.unique())
print(연상.IMAGE_NM.unique())

['2021' '2020' '2019' '2018' '2016-2017' '2015']
['중국' '일본' '대만' '태국' '말레이시아' '인도네시아' '인도' '베트남' '호주' '미국' '브라질' '아르헨티나'
 '프랑스' '영국' '러시아' '터키' 'UAE' '남아공']
['한국 음식(김치, 김, 볼고기 등)' '드라마' '뷰티 서비스(성형)' '뷰티 제품(화장품)' '한글(한국어)' '영화'
 'K-Pop' '한류스타(BTS, 이민호 등)' '예능프로고램' '한국전쟁 (The Korean War in 1950)'
 '온라인/모바일게임/e-sports/프로게이머' '한복/한옥/궁궐' 'IT제품/브랜드(휴대폰 TV, 컴퓨터 등)' '패션'
 '태권도' '자동차' '경제성장' '만화/웹툰/도서/문학' '스포츠/스포츠스타' '애니메이션' '캐릭터 상품/이모티콘'
 '올림픽/월드컵' '북핵위협/전쟁위험지역/북한' '코리안유튜버 영상' '한국 음식(김치, 김, 불고기 등)'
 'IT제품/브랜드(휴대폰, TV, 컴퓨터 등)' '패선' '온라인/모바일 게임 /e-sports/프로게이머' '올림픽 1월드컵'
 '기타' '뷰티서비스(성형)' '예능프로그램' '뷰티제품(화장품)' '북핵위협/전쟁위험지 역/북한'
 '한류스타(BTS, 이 민호 등)' '온라인/모바일 게임/e-sports/프로게이머'
 '한국전 쟁 (The Korean War in 1950)' '온라인/모바일 게 임 /e-sports/프로게 이 머'
 '스포즈/스포즈스타' '온라인/모바일 게 임/e-sports/프로게 이 머' '한복'
 '한국전쟁(The Korean War in 1950)' '북한' '북핵위협/전쟁위험지역' '온라인/모바일 게임'
 'e-sports/프로게이머' '도서/문학' '한옥/궁궐' '코리안 유튜버 영상' '만화/웹툰' '스포츠/스포츠 스타' '한류스타'
 '한국 음식' 'IT제품/브랜드' '한국 식당(음식점)' '코리안 유튜버 영상/방송' '문학/도서' '한글' 'K_Pop'
 'e_sports/프로게이머' '뷰티 제품' '뷰티(화장품및성형)' '한류스타(이민호,싸이등)' '관광지(서울,제주,남산타워등)'
 '한국음식(김치,불고기등)' 'IT산업(휴대폰,TV,컴퓨터등)' '북한/북핵위협/전쟁위험'
 '한국전쟁(TheKoreanWarin1950)' '코리안유튜버스타' '온라인/모바일게임' '만화' '캐릭터상품/이모티콘'
 '한옥/궁궐(경복궁,광화문,등)' '도서' '스포츠스타(김연아,박지성등)' '나이트라이프' '북한/북핵위협/전쟁위험지역' '없음'
 '북한(분단국가)' '한국전쟁' '게임' '스포츠스타' '새마을운동' '고요한아침의나라' '미용' '한식' '연예인'
 'IT 첨단산업' 'K-POP' '관광지' 'IT첨단산업' '올림픽/ 월드컵']

In [ ]:
연상['IMAGE_NM'] = 연상['IMAGE_NM'].apply(lambda x: x.replace(" ", ""))
연상['IMAGE_NM'].value_counts()

영화                 94
태권도                94
드라마                92
K-Pop              92
자동차                86
                   ..
K_Pop               1
올림픽1월드컵             1
패선                  1
예능프로고램              1
한국음식(김치,김,볼고기등)     1
Name: IMAGE_NM, Length: 75, dtype: int64

In [ ]:
# import matplotlib.pyplot as plt
# count = 연상['IMAGE_NM'].value_counts()
# plt.bar(count.index, count.values)

In [ ]:
###연상이미지_for_top10
#여러 가지 후보 중(글로 설명) top10 보여주기
#지금 너무 뒤죽박죽이라 형식 통일 필요

연상 = pd.read_csv('BOAZXNIA/REMIND_IMAGE_INFO_2021(연상이미지).csv')
연상['IMAGE_NM'] = 연상['IMAGE_NM'].apply(lambda x: x.replace(" ", ""))
print(연상['IMAGE_NM'].unique())

def for_image(x):
  if x in ['K-Pop', 'K-POP']:
    return 'K-POP'
  elif x in ['한국음식(김치,김,볼고기등)', '한국음식(김치,김,불고기등)', '한국음식(김치,불고기등)', '한식']:
    return '한식'
  elif x in ['드라마', '영화', '예능프로고램', '예능프로그램']:
    return '영화/드라마/예능'
  elif x in ['한류스타(BTS,이민호등)', '한류스타(이민호,싸이등)', '연예인']:
    return '한류스타'
  elif x in ['태권도', '스포츠/스포츠스타', '올림픽/월드컵', '올림픽1월드컵', '스포즈/스포즈스타', '스포츠스타(김연아,박지성등)', '스포츠스타']:
    return '스포츠'
  elif x in ['한국전쟁(TheKoreanWarin1950)', '북핵위협/전쟁위험지역/북한', '북한', 
             '북핵위협/전쟁위험지역', '북한/북핵위협/전쟁위험', '북한/북핵위협/전쟁위험지역',
             '북한(분단국가)' '한국전쟁']:
    return '북한/전쟁'
  elif x in ['IT제품/브랜드(휴대폰TV,컴퓨터등)', 'IT제품/브랜드(휴대폰,TV,컴퓨터등)', 'IT산업(휴대폰,TV,컴퓨터등)', 'IT첨단산업']:
    return 'IT'
  elif x in ['온라인/모바일게임/e-sports/프로게이머', '온라인/모바일게임', '게임']:
    return '게임'
  elif x in ['한글(한국어)', '한복/한옥/궁궐', '한복', '한옥/궁궐(경복궁,광화문,등)']:
    return '문화유산' 
  elif x in ['관광지(서울,제주,남산타워등)', '관광지']:
    return '관광'
  elif x in ['만화/웹툰/도서/문학', '애니메이션', '만화', '도서']:
    return '애니메이션/만화/웹툰/문학'
  elif x in ['뷰티서비스(성형)', '뷰티제품(화장품)', '패션', '패선', '뷰티제품', '뷰티(화장품및성형)', '미용']:
    return '뷰티/패션'
  elif x in ['경제성장', '새마을운동']:
    return '경제'
  else:
    return '기타'

연상['IMAGE_NM'] = 연상['IMAGE_NM'].apply(for_image)
print(연상['IMAGE_NM'].unique())

['한국음식(김치,김,볼고기등)' '드라마' '뷰티서비스(성형)' '뷰티제품(화장품)' '한글(한국어)' '영화' 'K-Pop'
 '한류스타(BTS,이민호등)' '예능프로고램' '한국전쟁(TheKoreanWarin1950)'
 '온라인/모바일게임/e-sports/프로게이머' '한복/한옥/궁궐' 'IT제품/브랜드(휴대폰TV,컴퓨터등)' '패션' '태권도'
 '자동차' '경제성장' '만화/웹툰/도서/문학' '스포츠/스포츠스타' '애니메이션' '캐릭터상품/이모티콘' '올림픽/월드컵'
 '북핵위협/전쟁위험지역/북한' '코리안유튜버영상' '한국음식(김치,김,불고기등)' 'IT제품/브랜드(휴대폰,TV,컴퓨터등)'
 '패선' '올림픽1월드컵' '기타' '예능프로그램' '스포즈/스포즈스타' '한복' '북한' '북핵위협/전쟁위험지역'
 '온라인/모바일게임' 'e-sports/프로게이머' '도서/문학' '한옥/궁궐' '만화/웹툰' '한류스타' '한국음식'
 'IT제품/브랜드' '한국식당(음식점)' '코리안유튜버영상/방송' '문학/도서' '한글' 'K_Pop'
 'e_sports/프로게이머' '뷰티제품' '뷰티(화장품및성형)' '한류스타(이민호,싸이등)' '관광지(서울,제주,남산타워등)'
 '한국음식(김치,불고기등)' 'IT산업(휴대폰,TV,컴퓨터등)' '북한/북핵위협/전쟁위험' '코리안유튜버스타' '만화'
 '한옥/궁궐(경복궁,광화문,등)' '도서' '스포츠스타(김연아,박지성등)' '나이트라이프' '북한/북핵위협/전쟁위험지역' '없음'
 '북한(분단국가)' '한국전쟁' '게임' '스포츠스타' '새마을운동' '고요한아침의나라' '미용' '한식' '연예인'
 'IT첨단산업' 'K-POP' '관광지']
['한식' '영화/드라마/예능' '뷰티/패션' '문화유산' 'K-POP' '한류스타' '북한/전쟁' '게임' 'IT' '스포츠'
 '기타' '경제' '애니메이션/만화/웹툰/문학' '관광']

In [ ]:
연상.to_csv('연상이미지.csv', encoding='utf-8-sig', index=False)

### __문화컨텐츠소비비중__
* https://www.culture.go.kr/bigdata/user/data_market/detail.do?id=5193c560-3604-11eb-af9a-4b03f0a582d6

In [ ]:
소비 = pd.read_csv('BOAZXNIA/CLTUR_CNTNTS_CNSMP_INFO_2021(문화컨텐츠소비비중).csv')
소비

,IEM_NM,ALL_TOTAL_CO,MALE_RATE,FEMALE_RATE,ALL_N10S_RATE,ALL_N20S_RATE,ALL_N30S_RATE,ALL_N40S_RATE,ALL_N50S_RATE,REPRT_YEAR_CN,EXAMIN_COUNTRY_NM,CNTNTS_URL
0,한국 문화콘텐츠 소비(시간),18,16.65,19.69,22.03,20.68,13.26,13.44,19.87,2021,중국,드라마
1,소비 비중(%),29,27.92,30.80,29.99,31.80,26.40,28.36,30.91,2021,중국,드라마
2,월평균 지출 금액($),7,8.12,6.82,6.08,7.14,6.42,5.46,20.56,2021,중국,드라마
3,한국 문화콘텐츠 소비(시간),13,11.76,14.76,14.25,13.65,13.17,8.31,15.45,2021,중국,예능
4,소비 비중(%),28,25.52,31.29,24.85,27.79,28.91,30.65,37.55,2021,중국,예능
...,...,...,...,...,...,...,...,...,...,...,...,...
2593,월평균 지출 금액($),9,8.50,8.57,8.80,9.11,8.48,8.55,7.02,2021,아르헨티나,패션
2594,소비 비중(%),19,20.35,18.02,17.82,21.56,18.71,13.50,13.00,2021,아르헨티나,뷰티
2595,월평균 지출 금액($),8,9.01,8.17,9.34,7.66,9.86,7.42,4.96,2021,아르헨티나,뷰티
2596,소비 비중(%),13,13.58,12.95,15.45,16.47,9.63,12.19,11.07,2021,아르헨티나,음식
2597,월평균 지출 금액($),8,8.31,7.95,9.89,7.56,7.25,8.67,7.30,2021,아르헨티나,음식

In [ ]:
print(소비.REPRT_YEAR_CN.unique())
print(소비.EXAMIN_COUNTRY_NM.unique())
print(소비.IEM_NM.unique())

['2021' '2020' '2019' '2018' '2016-2017']
['중국' '일본' '대만' '태국' '말레이시아' '인도네시아' '인도' '베트남' '호주' '미국' '브라질' '프랑스' '영국'
 '러시아' '터키' 'UAE' '남아공' '아르헨티나']
['한국 문화콘텐츠 소비(시간)' '소비 비중(%)' '월평균 지출 금액($)' '한국 문화콘텐츠 소비(3개월,편)'
 '월평균 지출 금액(3개월,$)' '전체 소비량(시간)' '전체 소비량(편)' '한국 문화콘텐츠 소비(편)' '전체 소비량($)'
 '한국 문화콘텐츠 소비($)' '전체소비량(시간)' '한류콘텐츠소비량(시간)' '소비비중(%)' '소비비중 (%)'
 '전체소비량($)' '한류콘텐츠소비량($)']

In [ ]:
소비.REPRT_YEAR_CN.value_counts()

2020         629
2019         592
2021         540
2018         432
2016-2017    405
Name: REPRT_YEAR_CN, dtype: int64

In [ ]:
# 소비 = 소비[(소비.REPRT_YEAR_CN == '2019') | (소비.REPRT_YEAR_CN == '2020') | (소비.REPRT_YEAR_CN == '2021')]
# 소비.to_csv('문화콘텐츠소비비중.csv', encoding='utf-8-sig', index=False)

In [ ]:
##문화콘텐츠소비비중 전처리
소비 = pd.read_csv('BOAZXNIA/CLTUR_CNTNTS_CNSMP_INFO_2021(문화컨텐츠소비비중).csv')
print(소비.CNTNTS_URL.unique())

def for_contents(x):
  if x in ['드라마', 'TV드라마']:
    return '드라마'
  elif x in ['예능', '예능,프로그램']:
    return '예능'
  elif x in ['영화']:
    return '영화'
  elif x in ['음악', '음악,(K-Pop)' ]:
    return 'K-POP'
  elif x in ['애니메이션', '웹툰', '도서', '출판물', '애니메이션/,만화/캐릭터', '도서,(출판물)']:
    return '애니메이션/만화/웹툰/문학'
  elif x in ['게임', '온라인/,모바일게임']:
    return '게임'
  elif x in ['패션', '뷰티', '패션/뷰티']:
    return '패션/뷰티'
  elif x in ['음식', '한식']:
    return '음식'

소비['CNTNTS_URL'] = 소비['CNTNTS_URL'].apply(for_contents)
print(소비['CNTNTS_URL'].unique())

['드라마' '예능' '영화' '음악' '애니메이션' '웹툰' '도서' '게임' '패션' '뷰티' '음식' '출판물' '한식'
 'TV드라마' '예능,프로그램' '음악,(K-Pop)' '애니메이션/,만화/캐릭터' '온라인/,모바일게임' '패션/뷰티'
 '도서,(출판물)']
['드라마' '예능' '영화' 'K-POP' '애니메이션/만화/웹툰/문학' '게임' '패션/뷰티' '음식']

In [ ]:
소비.to_csv('문화콘텐츠소비비중.csv', encoding='utf-8-sig', index=False)

### __컨텐츠호감도인기도__
* https://www.culture.go.kr/bigdata/user/data_market/detail.do?id=5a046a60-3604-11eb-af9a-4b03f0a582d6

In [ ]:
호감 = pd.read_csv('BOAZXNIA/CLTUR_POPULAR_DGREE_INFO_2021(컨텐츠호감도인기도).csv')
호감

,POPULAR_DGREE_CN,ALL_TOTAL_CO,MALE_RATE,FEMALE_RATE,ALL_N10S_RATE,ALL_N20S_RATE,ALL_N30S_RATE,ALL_N40S_RATE,ALL_N50S_RATE,REPRT_YEAR_CN,EXAMIN_COUNTRY_NM,CNTNTS_URL
0,대중적 인기,34,34.0,34.8,32.0,35.2,32.8,38.5,33.3,2020,중국,드라마
1,보통 인기,39,36.4,40.8,35.2,40.8,44.0,33.7,38.1,2020,중국,드라마
2,소수 마니아 인기,23,26.4,20.4,28.0,21.6,20.8,23.1,23.8,2020,중국,드라마
3,거의 이용 안함,4,3.2,4.0,4.8,2.4,2.4,4.8,4.8,2020,중국,드라마
4,대중적 인기,33,30.8,34.4,32.0,38.4,31.2,27.9,33.3,2020,중국,예능
...,...,...,...,...,...,...,...,...,...,...,...,...
3621,이용하는 사람이 거의 없다,12,14.5,9.5,14.0,9.0,9.0,18.2,0.0,2021,남아공,음식
3622,일부 매니아증에서 인기가 있는 상태,16,17.0,15.0,18.0,16.0,16.0,13.6,16.7,2021,남아공,음식
3623,일부 매니아층 뿐만 아니라 일반인들도 상당수 인지,33,33.5,32.0,31.0,27.0,33.0,35.2,75.0,2021,남아공,음식
3624,일반인에게 널리 알려져 있고 관련 상품이 판매됨,23,20.5,25.5,21.0,25.0,28.0,20.5,0.0,2021,남아공,음식
3625,일반인에게 널리 인기 있고 관련 상품의 판매가 원활,16,14.5,18.0,16.0,23.0,14.0,12.5,8.3,2021,남아공,음식

In [ ]:
print(호감.REPRT_YEAR_CN.unique())
print(호감.EXAMIN_COUNTRY_NM.unique())
print(호감.CNTNTS_URL.unique())
print(호감.POPULAR_DGREE_CN.unique())

['2020' '2019' '2018' '2016-2017' '2021']
['중국' '일본' '대만' '태국' '말레이시아' '인도네시아' '인도' '베트남' '호주' '미국' '브라질' '프랑스' '영국'
 '러시아' '터키' 'UAE' '남아공' '아르헨티나']
['드라마' '예능' '영화' '음악' '애니메이션' '도서/만화' '웹툰' '게임' '패션' '뷰티' '한식' '도서'
 'TV드라마' '음악(K-Pop)' '만화' '캐릭터상품' '온라인/모바일게임' '패션/뷰티' '음식' '도서(출판물)'
 'TV드라마/예능' '애니메이션/만화/캐릭터']
['대중적 인기' '보통 인기' '소수 마니아 인기' '거의 이용 안함' '대중적인기' '보통인기' '소수마니아인기' '거의이용안함'
 '이용하는 사람이 거의 없다' '일부 매니아증에서 인기가 있는 상태' '일부 매니아층 뿐만 아니라 일반인들도 상당수 인지'
 '일반인에게 널리 알려져 있고 관련 상품이 판매됨' '일반인에게 널리 인기 있고 관련 상품의 판매가 원활']

In [ ]:
호감['CNTNTS_URL'].value_counts()

영화              346
애니메이션           286
예능              286
드라마             222
음악              222
웹툰              222
패션              222
뷰티              222
온라인/모바일게임       214
음식              214
도서/만화           158
게임              132
한식              132
도서(출판물)         124
음악(K-Pop)       124
패션/뷰티           124
도서               64
캐릭터상품            64
만화               64
TV드라마            64
TV드라마/예능         60
애니메이션/만화/캐릭터     60
Name: CNTNTS_URL, dtype: int64

In [ ]:
호감.REPRT_YEAR_CN.value_counts()

2021         990
2020         748
2019         704
2018         704
2016-2017    480
Name: REPRT_YEAR_CN, dtype: int64

In [ ]:
호감 = 호감[(호감.REPRT_YEAR_CN == '2019') | (호감.REPRT_YEAR_CN == '2020') | (호감.REPRT_YEAR_CN == '2021')]
호감.to_csv('콘텐츠호감도인기도.csv', encoding='utf-8-sig', index=False)

In [ ]:
###콘텐츠호감도인기도 전처리
호감 = pd.read_csv('BOAZXNIA/CLTUR_POPULAR_DGREE_INFO_2021(컨텐츠호감도인기도).csv')
print(호감.CNTNTS_URL.unique())

def for_contents(x):
  if x in ['드라마', 'TV드라마']:
    return '드라마'
  elif x in ['예능', 'TV드라마/예능']:
    return '예능'
  elif x in ['영화']:
    return '영화'
  elif x in ['음악', '음악(K-Pop)']:
    return 'K-POP'
  elif x in ['애니메이션', '도서/만화', '웹툰', '도서', '도서(출판물)', '캐릭터상품', '만화', '애니메이션/만화/캐릭터']:
    return '애니메이션/만화/웹툰/문학'
  elif x in ['게임', '온라인/모바일게임']:
    return '게임'
  elif x in ['패션', '뷰티', '패션/뷰티']:
    return '패션/뷰티'
  elif x in ['한식', '음식']:
    return '음식'

호감['CNTNTS_URL'] = 호감['CNTNTS_URL'].apply(for_contents)
print(호감['CNTNTS_URL'].unique())

['드라마' '예능' '영화' '음악' '애니메이션' '도서/만화' '웹툰' '게임' '패션' '뷰티' '한식' '도서'
 'TV드라마' '음악(K-Pop)' '만화' '캐릭터상품' '온라인/모바일게임' '패션/뷰티' '음식' '도서(출판물)'
 'TV드라마/예능' '애니메이션/만화/캐릭터']
['드라마' '예능' '영화' 'K-POP' '애니메이션/만화/웹툰/문학' '게임' '패션/뷰티' '음식']

In [ ]:
호감.to_csv('콘텐츠호감도인기도.csv', encoding='utf-8-sig', index=False)

### __세종학당__
* https://www.culture.go.kr/bigdata/user/data_market/detail.do?id=f7775c50-6272-11ea-8b67-7b32ce18203a
* 칼럼 수정 및 wide form -> long form 변형

In [ ]:
세종 = pd.read_csv('BOAZXNIA/KC_SEJONGKOREALANGAUGEINSTITUTE_2020(세종학당).csv')
세종

,SURVEY_BASE_DATE_YY,TOTAL_NATION_CO,TOTAL_PLACE_CO,STUDENT_CO,GRADUATE_CO,ONLINE_STUDENT_CO,ONLINE_CLASS_CO,FILE_NAME,BASE_YMD
0,2016,58,174,49549,17289,82469,668445,KC_SEJONGKOREALANGAUGEINSTITUTE_2020,20210126
1,2017,54,171,56202,18341,120241,793363,KC_SEJONGKOREALANGAUGEINSTITUTE_2020,20210126
2,2018,57,172,61810,19738,166719,926295,KC_SEJONGKOREALANGAUGEINSTITUTE_2020,20210126
3,2019,60,180,72713,21475,200916,917684,KC_SEJONGKOREALANGAUGEINSTITUTE_2020,20210126

In [ ]:
#칼럼 수정
세종 = 세종.iloc[:, :-2]
세종 = 세종.rename(columns={'SURVEY_BASE_DATE_YY': '조사연도',
                         'TOTAL_NATION_CO': '총 국가 수',
                         'TOTAL_PLACE_CO': '총 장소 수',
                         'STUDENT_CO': '학생 수',
                         'GRADUATE_CO': '졸업생 수',
                         'ONLINE_STUDENT_CO': '온라인 학생 수',
                        'ONLINE_CLASS_CO': '온라인 수업 수'
                        })
세종

   조사연도  총 국가 수  총 장소 수   학생 수  졸업생 수  온라인 학생 수  온라인 수업 수
0  2016      58     174  49549  17289     82469    668445
1  2017      54     171  56202  18341    120241    793363
2  2018      57     172  61810  19738    166719    926295
3  2019      60     180  72713  21475    200916    917684

In [ ]:
#wide -> long by melt
세종 = 세종.melt(id_vars='조사연도')
세종

    조사연도  variable   value
0   2016    총 국가 수      58
1   2017    총 국가 수      54
2   2018    총 국가 수      57
3   2019    총 국가 수      60
4   2016    총 장소 수     174
5   2017    총 장소 수     171
6   2018    총 장소 수     172
7   2019    총 장소 수     180
8   2016      학생 수   49549
9   2017      학생 수   56202
10  2018      학생 수   61810
11  2019      학생 수   72713
12  2016     졸업생 수   17289
13  2017     졸업생 수   18341
14  2018     졸업생 수   19738
15  2019     졸업생 수   21475
16  2016  온라인 학생 수   82469
17  2017  온라인 학생 수  120241
18  2018  온라인 학생 수  166719
19  2019  온라인 학생 수  200916
20  2016  온라인 수업 수  668445
21  2017  온라인 수업 수  793363
22  2018  온라인 수업 수  926295
23  2019  온라인 수업 수  917684

In [ ]:
세종.to_csv('세종학당.csv', encoding='utf-8-sig', index=False)

### __For Geocoding__
* 구글 위경도 변환 -> limit 존재하므로 중복 제거하고 진행

In [ ]:
df = pd.DataFrame(set(list(소비.EXAMIN_COUNTRY_NM.unique()) + list(호감.EXAMIN_COUNTRY_NM.unique())))
df.to_csv('countries_for_geocoding.csv', encoding='utf-8-sig', index=False)

In [ ]:
df

        0
0      호주
1   인도네시아
2   말레이시아
3      태국
4     브라질
5      인도
6      터키
7     남아공
8     베트남
9     프랑스
10     중국
11     영국
12    UAE
13    러시아
14     대만
15     미국
16     일본
17  아르헨티나

###__For 연상이미지__

In [ ]:
###연상이미지_for_top10
#여러 가지 후보 중(글로 설명) top10 보여주기
#지금 너무 뒤죽박죽이라 형식 통일 필요

연상 = pd.read_csv('BOAZXNIA/REMIND_IMAGE_INFO_2021(연상이미지).csv')
연상['IMAGE_NM'] = 연상['IMAGE_NM'].apply(lambda x: x.replace(" ", ""))
print(연상['IMAGE_NM'].unique())

def for_image(x):
  if x in ['K-Pop', 'K-POP']:
    return 'K-POP'
  elif x in ['한국음식(김치,김,볼고기등)', '한국음식(김치,김,불고기등)', '한국음식(김치,불고기등)', '한식']:
    return '한식'
  elif x in ['드라마', '영화', '예능프로고램', '예능프로그램']:
    return '영화/드라마/예능'
  elif x in ['한류스타(BTS,이민호등)', '한류스타(이민호,싸이등)', '연예인']:
    return '한류스타'
  elif x in ['태권도', '스포츠/스포츠스타', '올림픽/월드컵', '올림픽1월드컵', '스포즈/스포즈스타', '스포츠스타(김연아,박지성등)', '스포츠스타']:
    return '스포츠'
  elif x in ['한국전쟁(TheKoreanWarin1950)', '북핵위협/전쟁위험지역/북한', '북한', '북핵위협/전쟁위험지역', 
             '북한/북핵위협/전쟁위험', '북한/북핵위협/전쟁위험지역', '북한(분단국가)' '한국전쟁']:
    return '북한/전쟁'
  elif x in ['IT제품/브랜드(휴대폰TV,컴퓨터등)', 'IT제품/브랜드(휴대폰,TV,컴퓨터등)', 'IT산업(휴대폰,TV,컴퓨터등)', 'IT첨단산업']:
    return 'IT'
  elif x in ['온라인/모바일게임/e-sports/프로게이머', '온라인/모바일게임', '게임']:
    return '게임'
  elif x in ['한글(한국어)', '한복/한옥/궁궐', '한복', '한옥/궁궐(경복궁,광화문,등)']:
    return '문화유산' 
  elif x in ['관광지(서울,제주,남산타워등)', '관광지']:
    return '관광'
  elif x in ['만화/웹툰/도서/문학', '애니메이션', '만화', '도서']:
    return '애니메이션/만화/웹툰/문학'
  elif x in ['뷰티서비스(성형)', '뷰티제품(화장품)', '패션', '패선', '뷰티제품', '뷰티(화장품및성형)', '미용']:
    return '뷰티/패션'
  elif x in ['경제성장', '새마을운동']:
    return '경제'
  else:
    return '기타'

연상['IMAGE_NM'] = 연상['IMAGE_NM'].apply(for_image)
print(연상['IMAGE_NM'].unique())

### __For 콘텐츠__

In [ ]:
###문화콘텐츠소비비중 전처리
소비 = pd.read_csv('BOAZXNIA/CLTUR_CNTNTS_CNSMP_INFO_2021(문화컨텐츠소비비중).csv')
print(소비.CNTNTS_URL.unique())

def for_contents(x):
  if x in ['드라마', 'TV드라마']:
    return '드라마'
  elif x in ['예능', '예능,프로그램']:
    return '예능'
  elif x in ['영화']:
    return '영화'
  elif x in ['음악', '음악,(K-Pop)' ]:
    return 'K-POP'
  elif x in ['애니메이션', '웹툰', '도서', '출판물', '애니메이션/,만화/캐릭터', '도서,(출판물)']:
    return '애니메이션/만화/웹툰/문학'
  elif x in ['게임', '온라인/,모바일게임']:
    return '게임'
  elif x in ['패션', '뷰티', '패션/뷰티']:
    return '패션/뷰티'
  elif x in ['음식', '한식']:
    return '음식'

소비['CNTNTS_URL'] = 소비['CNTNTS_URL'].apply(for_contents)
print(소비['CNTNTS_URL'].unique())

In [ ]:
###콘텐츠호감도인기도 전처리
호감 = pd.read_csv('BOAZXNIA/CLTUR_POPULAR_DGREE_INFO_2021(컨텐츠호감도인기도).csv')
print(호감.CNTNTS_URL.unique())

def for_contents(x):
  if x in ['드라마', 'TV드라마']:
    return '드라마'
  elif x in ['예능', 'TV드라마/예능']:
    return '예능'
  elif x in ['영화']:
    return '영화'
  elif x in ['음악', '음악(K-Pop)']:
    return 'K-POP'
  elif x in ['애니메이션', '도서/만화', '웹툰', '도서', '도서(출판물)', '캐릭터상품', '만화', '애니메이션/만화/캐릭터']:
    return '애니메이션/만화/웹툰/문학'
  elif x in ['게임', '온라인/모바일게임']:
    return '게임'
  elif x in ['패션', '뷰티', '패션/뷰티']:
    return '패션/뷰티'
  elif x in ['한식', '음식']:
    return '음식'

호감['CNTNTS_URL'] = 호감['CNTNTS_URL'].apply(for_contents)
print(호감['CNTNTS_URL'].unique())  

호감.to_csv('콘텐츠호감도인기도.csv', encoding='utf-8-sig', index=False)

### __For Donut__

In [11]:
###문화콘텐츠소비비중 전처리
def for_content_spend(x):
  if x in ['소비 비중(%)', '소비비중(%)', '소비비중 (%)']:
    return '소비비중(%)'
  elif x in ['한국 문화콘텐츠 소비(3개월,편)', '한국 문화콘텐츠 소비(편)']:
    return '한국 문화콘텐츠 소비량(편)'
  elif x in ['한국 문화콘텐츠 소비(시간)', '한류콘텐츠소비량(시간)']:
    return '한국문화콘텐츠 소비량(시간)'
  elif x in ['한국 문화콘텐츠 소비($)', '한류콘텐츠소비량($)']:
    return '한국 문화콘텐츠 소비량($)'
  elif x in ['월평균 지출 금액($)', '월평균 지출 금액(3개월,$)' ]:
    return '월평균 지출 금액($)'
  elif x in ['전체 소비량(시간)', '전체소비량(시간)']:
    return '전체 소비량(시간)'
  elif x in ['전체 소비량(편)']:
    return '전체 소비량(편)' 
  elif x in ['전체 소비량($)', '전체소비량($)']:
    return '전체 소비량($)' 

소비 = pd.read_csv('BOAZXNIA/CLTUR_CNTNTS_CNSMP_INFO_2021(문화컨텐츠소비비중).csv')
소비['IEM_NM'] = 소비['IEM_NM'].apply(for_content_spend)
소비 = 소비[['IEM_NM', 'MALE_RATE', 'FEMALE_RATE']]
소비 = 소비.melt(id_vars='IEM_NM')
소비.to_csv('문화콘텐츠소비비중_donut2.csv', encoding='utf-8-sig', index=False)

In [ ]:
print(소비.IEM_NM.unique())
print(소비.IEM_NM.value_counts())

['한국 문화콘텐츠 소비(시간)' '소비 비중(%)' '월평균 지출 금액($)' '한국 문화콘텐츠 소비(3개월,편)'
 '월평균 지출 금액(3개월,$)' '전체 소비량(시간)' '전체 소비량(편)' '한국 문화콘텐츠 소비(편)' '전체 소비량($)'
 '한국 문화콘텐츠 소비($)' '전체소비량(시간)' '한류콘텐츠소비량(시간)' '소비비중(%)' '소비비중 (%)'
 '전체소비량($)' '한류콘텐츠소비량($)']
소비 비중(%)              528
월평균 지출 금액($)          411
한국 문화콘텐츠 소비(시간)       326
소비비중 (%)              248
전체소비량(시간)             217
한류콘텐츠소비량(시간)          217
전체 소비량(시간)            200
전체 소비량($)              99
한국 문화콘텐츠 소비($)         99
전체소비량($)               62
한류콘텐츠소비량($)            62
전체 소비량(편)              31
한국 문화콘텐츠 소비(편)         31
소비비중(%)                31
한국 문화콘텐츠 소비(3개월,편)     18
월평균 지출 금액(3개월,$)       18
Name: IEM_NM, dtype: int64

In [ ]:
#소비편수: 3개월 붙고 안 붙고 비슷함 
print(소비[소비['IEM_NM']=='한국 문화콘텐츠 소비(편)']['ALL_TOTAL_CO'].mean())
print(소비[소비['IEM_NM']=='한국 문화콘텐츠 소비(3개월,편)']['ALL_TOTAL_CO'].mean())
#지출금액: 평균 난리남 -> 중앙값 비슷한거보니까 아웃라이어 차이인듯??
print(소비[소비['IEM_NM']=='월평균 지출 금액($)']['ALL_TOTAL_CO'].mean())
print(소비[소비['IEM_NM']=='월평균 지출 금액(3개월,$)']['ALL_TOTAL_CO'].mean())
print(소비[소비['IEM_NM']=='월평균 지출 금액($)']['ALL_TOTAL_CO'].median())
print(소비[소비['IEM_NM']=='월평균 지출 금액(3개월,$)']['ALL_TOTAL_CO'].median())
##결론: 둘 다 3개월 떼고 생각해도 될 듯!

5.935483870967742
6.222222222222222
1464.890510948905
14.0
9.0
9.5

In [12]:
###콘텐츠호감도인기도 전처리
def for_content_love(x):
  if x in ['대중적 인기', '대중적인기', '일반인에게 널리 알려져 있고 관련 상품이 판매됨', '일반인에게 널리 인기 있고 관련 상품의 판매가 원활']:
    return '대중적 인기'
  elif x in ['보통 인기', '보통인기', '일부 매니아층 뿐만 아니라 일반인들도 상당수 인지']:
    return '보통 인기'
  elif x in ['소수 마니아 인기', '소수마니아인기', '일부 매니아증에서 인기가 있는 상태']:
    return '소수 마니아 인기'
  elif x in ['거의 이용 안함', '거의이용안함', '이용하는 사람이 거의 없다']:
    return '거의 이용 안함'
  elif x in []:
    return '한국문화콘텐츠 소비비중(%)'
  elif x in []:
    return '한국문화콘텐츠 소비비중(%)' 

호감 = pd.read_csv('BOAZXNIA/CLTUR_POPULAR_DGREE_INFO_2021(컨텐츠호감도인기도).csv')
호감['POPULAR_DGREE_CN'] = 호감['POPULAR_DGREE_CN'].apply(for_content_love)
호감 = 호감[['POPULAR_DGREE_CN', 'MALE_RATE', 'FEMALE_RATE']]
호감 = 호감.melt(id_vars='POPULAR_DGREE_CN')
호감.to_csv('콘텐츠호감도인기도_donut2.csv', encoding='utf-8-sig', index=False)

In [ ]:
print(호감.POPULAR_DGREE_CN.unique())
print(호감.POPULAR_DGREE_CN.value_counts())
print('2021:', 호감[호감['REPRT_YEAR_CN']=='2021'].POPULAR_DGREE_CN.unique())
print('not 2021:', 호감[호감['REPRT_YEAR_CN']!='2021'].POPULAR_DGREE_CN.unique())
print(len(호감[호감['REPRT_YEAR_CN']=='2021']), 198*5)
##결론: 2021년에 설문문항이 바뀐듯?? 어떻게 합칠지는 좀더 고민

['대중적 인기' '보통 인기' '소수 마니아 인기' '거의 이용 안함' '대중적인기' '보통인기' '소수마니아인기' '거의이용안함'
 '이용하는 사람이 거의 없다' '일부 매니아증에서 인기가 있는 상태' '일부 매니아층 뿐만 아니라 일반인들도 상당수 인지'
 '일반인에게 널리 알려져 있고 관련 상품이 판매됨' '일반인에게 널리 인기 있고 관련 상품의 판매가 원활']
대중적 인기                          363
보통 인기                           363
소수 마니아 인기                       363
거의 이용 안함                        363
대중적인기                           296
보통인기                            296
소수마니아인기                         296
거의이용안함                          296
이용하는 사람이 거의 없다                  198
일부 매니아증에서 인기가 있는 상태             198
일부 매니아층 뿐만 아니라 일반인들도 상당수 인지     198
일반인에게 널리 알려져 있고 관련 상품이 판매됨      198
일반인에게 널리 인기 있고 관련 상품의 판매가 원활    198
Name: POPULAR_DGREE_CN, dtype: int64
2021: ['이용하는 사람이 거의 없다' '일부 매니아증에서 인기가 있는 상태' '일부 매니아층 뿐만 아니라 일반인들도 상당수 인지'
 '일반인에게 널리 알려져 있고 관련 상품이 판매됨' '일반인에게 널리 인기 있고 관련 상품의 판매가 원활']
not 2021: ['대중적 인기' '보통 인기' '소수 마니아 인기' '거의 이용 안함' '대중적인기' '보통인기' '소수마니아인기' '거의이용안함']
990 990